version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskmanager-postgres
    environment:
      POSTGRES_DB: taskmanager_users
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - taskmanager-network

  redis:
    image: redis:7-alpine
    container_name: taskmanager-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - taskmanager-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: taskmanager-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - taskmanager-network

  eureka-server:
    image: steeltoeoss/eureka-server:latest
    container_name: taskmanager-eureka
    ports:
      - "8761:8761"
    networks:
      - taskmanager-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  taskmanager-network:
    driver: bridge